Step 2: Acoustic Model(CTC) Training...
Traceback (most recent call last):
  File "steps/train_ctc.py", line 12, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Step 2: Acoustic Model(CTC) Training...
exp_name                                          :ctc_fbank_cnn
checkpoint_dir                                    :checkpoint/
vocab_file                                        :data/units
train_scp_path                                    :data/train/fbank.scp
train_lab_path                                    :data/train/phn_text
train_trans_path                                  :data/train/transcript_phn_text
valid_scp_path                                    :data/dev/fbank.scp
valid_lab_path                                    :data/dev/phn_text
valid_trans_path                                  :data/dev/transcript_phn_text
left_ctx                                          :0
right_ctx                                         :2
n_skip_frame                                      :2
n_downsample                                      :2
num_workers                                       :1
shuffle_train                                     :True
feature_dim                                       :81
output_class_dim                                  :39
mel                                               :False
feature_type                                      :fbank
rnn_input_size                                    :243
rnn_hidden_size                                   :384
rnn_layers                                        :4
rnn_type                                          :nn.LSTM
bidirectional                                     :True
batch_norm                                        :True
drop_out                                          :0.2
add_cnn                                           :True
layers                                            :2
channel                                           :[(1, 32), (32, 32)]
kernel_size                                       :[(3, 3), (3, 3)]
stride                                            :[(1, 2), (2, 2)]
padding                                           :[(1, 1), (1, 1)]
pooling                                           :None
activation_function                               :relu
use_gpu                                           :True
init_lr                                           :0.001
num_epoches                                       :500
end_adjust_acc                                    :2
lr_decay                                          :0.5
batch_size                                        :8
weight_decay                                      :0.0005
seed                                              :1
verbose_step                                      :50
test_scp_path                                     :data/test/fbank.scp
test_lab_path                                     :data/test/phn_text
test_trans_path                                   :data/test/transcript_phn_text
decode_type                                       :Beam
beam_width                                        :10
lm_alpha                                          :0
lm_path                                           :data/lm_phone_bg.arpa
Reading vocabulary from data/units
Vocabulary size is 43
Reading 8100 lines from data/train/phn_text
Reading 897 lines from data/dev/phn_text
Traceback (most recent call last):
  File "steps/train_ctc.py", line 263, in <module>
    main(conf)
  File "steps/train_ctc.py", line 127, in main
    model = model.to(device)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 140, in _apply
    self.flatten_parameters()
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 129, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 10.91 GiB total capacity; 55.84 MiB already allocated; 4.50 MiB free; 62.00 MiB reserved in total by PyTorch)
Step 2: Acoustic Model(CTC) Training...
exp_name                                          :ctc_fbank_cnn
checkpoint_dir                                    :checkpoint/
vocab_file                                        :data/units
train_scp_path                                    :data/train/fbank.scp
train_lab_path                                    :data/train/phn_text
train_trans_path                                  :data/train/transcript_phn_text
valid_scp_path                                    :data/dev/fbank.scp
valid_lab_path                                    :data/dev/phn_text
valid_trans_path                                  :data/dev/transcript_phn_text
left_ctx                                          :0
right_ctx                                         :2
n_skip_frame                                      :2
n_downsample                                      :2
num_workers                                       :1
shuffle_train                                     :True
feature_dim                                       :81
output_class_dim                                  :39
mel                                               :False
feature_type                                      :fbank
rnn_input_size                                    :243
rnn_hidden_size                                   :384
rnn_layers                                        :4
rnn_type                                          :nn.LSTM
bidirectional                                     :True
batch_norm                                        :True
drop_out                                          :0.2
add_cnn                                           :True
layers                                            :2
channel                                           :[(1, 32), (32, 32)]
kernel_size                                       :[(3, 3), (3, 3)]
stride                                            :[(1, 2), (2, 2)]
padding                                           :[(1, 1), (1, 1)]
pooling                                           :None
activation_function                               :relu
use_gpu                                           :True
init_lr                                           :0.001
num_epoches                                       :500
end_adjust_acc                                    :2
lr_decay                                          :0.5
batch_size                                        :8
weight_decay                                      :0.0005
seed                                              :1
verbose_step                                      :50
test_scp_path                                     :data/test/fbank.scp
test_lab_path                                     :data/test/phn_text
test_trans_path                                   :data/test/transcript_phn_text
decode_type                                       :Beam
beam_width                                        :10
lm_alpha                                          :0
lm_path                                           :data/lm_phone_bg.arpa
Reading vocabulary from data/units
Vocabulary size is 43
Reading 8100 lines from data/train/phn_text
Reading 897 lines from data/dev/phn_text
Traceback (most recent call last):
  File "steps/train_ctc.py", line 263, in <module>
    main(conf)
  File "steps/train_ctc.py", line 127, in main
    model = model.to(device)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 425, in to
    return self._apply(convert)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 140, in _apply
    self.flatten_parameters()
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 129, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 10.91 GiB total capacity; 55.84 MiB already allocated; 4.50 MiB free; 62.00 MiB reserved in total by PyTorch)
Step 2: Acoustic Model(CTC) Training...
Setting up a new session...
Traceback (most recent call last):
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f527474c198>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f527474c198>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ljh/anaconda3/envs/py36/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f527474c198>: Failed to establish a new connection: [Errno 111] Connection refused',))
[Errno 111] Connection refused
exp_name                                          :ctc_fbank_cnn
checkpoint_dir                                    :checkpoint/
vocab_file                                        :data/units
train_scp_path                                    :data/train/fbank.scp
train_lab_path                                    :data/train/phn_text
train_trans_path                                  :data/train/transcript_phn_text
valid_scp_path                                    :data/dev/fbank.scp
valid_lab_path                                    :data/dev/phn_text
valid_trans_path                                  :data/dev/transcript_phn_text
left_ctx                                          :0
right_ctx                                         :2
n_skip_frame                                      :2
n_downsample                                      :2
num_workers                                       :1
shuffle_train                                     :True
feature_dim                                       :81
output_class_dim                                  :39
mel                                               :False
feature_type                                      :fbank
rnn_input_size                                    :243
rnn_hidden_size                                   :384
rnn_layers                                        :4
rnn_type                                          :nn.LSTM
bidirectional                                     :True
batch_norm                                        :True
drop_out                                          :0.2
add_cnn                                           :True
layers                                            :2
channel                                           :[(1, 32), (32, 32)]
kernel_size                                       :[(3, 3), (3, 3)]
stride                                            :[(1, 2), (2, 2)]
padding                                           :[(1, 1), (1, 1)]
pooling                                           :None
activation_function                               :relu
use_gpu                                           :True
init_lr                                           :0.001
num_epoches                                       :500
end_adjust_acc                                    :2
lr_decay                                          :0.5
batch_size                                        :8
weight_decay                                      :0.0005
seed                                              :1
verbose_step                                      :50
test_scp_path                                     :data/test/fbank.scp
test_lab_path                                     :data/test/phn_text
test_trans_path                                   :data/test/transcript_phn_text
decode_type                                       :Beam
beam_width                                        :10
lm_alpha                                          :0
lm_path                                           :data/lm_phone_bg.arpa
Reading vocabulary from data/units
Vocabulary size is 43
Reading 8100 lines from data/train/phn_text
Reading 897 lines from data/dev/phn_text
Number of parameters 21246432
0 Sequential(
  (0): LayerCNN(
    (conv): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 2), padding=(1, 1))
    (batch_norm): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activation): ReLU(inplace=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (1): LayerCNN(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (batch_norm): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activation): ReLU(inplace=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
)
1 Sequential(
  (0): BatchRNN(
    (rnn): LSTM(1952, 384, bias=False, bidirectional=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (1): BatchRNN(
    (batch_norm): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn): LSTM(768, 384, bias=False, bidirectional=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (2): BatchRNN(
    (batch_norm): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn): LSTM(768, 384, bias=False, bidirectional=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (3): BatchRNN(
    (batch_norm): BatchNorm1d(768, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn): LSTM(768, 384, bias=False, bidirectional=True)
    (dropout): Dropout(p=0.2, inplace=False)
  )
)
2 Embedding(42, 512)
3 LSTM(512, 384, batch_first=True, bidirectional=True)
4 Linear(in_features=768, out_features=768, bias=False)
5 Sequential(
  (0): BatchNorm1d(1536, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (1): Linear(in_features=1536, out_features=43, bias=False)
)
6 LogSoftmax()
{'num_epoches': 500, 'end_adjust_acc': 2, 'mel': False, 'seed': 1, 'decay': 0.5, 'learning_rate': 0.001, 'weight_decay': 0.0005, 'batch_size': 8, 'feature_type': 'fbank', 'n_feats': 81}
Exception in user code:
------------------------------------------------------------
Start training epoch: 1, learning_rate: 0.00100
Epoch = 1, step = 50, cur_loss = 120.2534, total_loss = 120.2534, total_wer = 0.8184
Epoch = 1, step = 100, cur_loss = 87.0675, total_loss = 103.6605, total_wer = 0.7451
Epoch = 1, step = 150, cur_loss = 74.7686, total_loss = 94.0298, total_wer = 0.6930
Epoch = 1, step = 200, cur_loss = 64.8532, total_loss = 86.7357, total_wer = 0.6464
Epoch = 1, step = 250, cur_loss = 60.3724, total_loss = 81.4630, total_wer = 0.6106
Epoch = 1, step = 300, cur_loss = 56.1204, total_loss = 77.2393, total_wer = 0.5824
Epoch = 1, step = 350, cur_loss = 49.6851, total_loss = 73.3030, total_wer = 0.5577
Epoch = 1, step = 400, cur_loss = 50.9514, total_loss = 70.5090, total_wer = 0.5367
Epoch = 1, step = 450, cur_loss = 47.8690, total_loss = 67.9935, total_wer = 0.5193
Epoch = 1, step = 500, cur_loss = 48.3072, total_loss = 66.0248, total_wer = 0.5057
Epoch = 1, step = 550, cur_loss = 47.2955, total_loss = 64.3222, total_wer = 0.4930
Epoch = 1, step = 600, cur_loss = 45.8402, total_loss = 62.7820, total_wer = 0.4813
Epoch = 1, step = 650, cur_loss = 44.0927, total_loss = 61.3444, total_wer = 0.4720
Epoch = 1, step = 700, cur_loss = 41.9990, total_loss = 59.9626, total_wer = 0.4622
Epoch = 1, step = 750, cur_loss = 40.6130, total_loss = 58.6726, total_wer = 0.4532
Epoch = 1, step = 800, cur_loss = 41.1896, total_loss = 57.5799, total_wer = 0.4450
Epoch = 1, step = 850, cur_loss = 40.6583, total_loss = 56.5845, total_wer = 0.4379
Epoch = 1, step = 900, cur_loss = 39.7663, total_loss = 55.6502, total_wer = 0.4312
Epoch = 1, step = 950, cur_loss = 38.5778, total_loss = 54.7516, total_wer = 0.4249
Epoch = 1, step = 1000, cur_loss = 39.9780, total_loss = 54.0129, total_wer = 0.4191
Epoch 1 Train done, total_loss: 53.7607, total_wer: 0.4177
Epoch 1 Valid done, total_loss: 51.0042, total_wer: 0.4044
loss on dev set is 51.0042
adjust_rate_count:0
adjust_time:0
epoch 1 done, cv acc is: 0.5956, time_used: 1.2219 minutes
Start training epoch: 2, learning_rate: 0.00100
